INSERT INTO projects (name, type, client, impact, description, technologies, tags, url, is_ai, sort_order) VALUES
  ('CBA TRBK HANA Modernisation', 'S/4HANA modernisation, performance, AI-assisted automation', 'Commonwealth Bank', 'Reduced data scrambling runtime from 240 hours to 6 hours (97% improvement). Built Node.js MCP server for controlled SAP RAP OData execution.', 'Supported CommBank SAP Transactional Banking HANA modernisation. Contributed to code remediation, DB2-to-HANA query translation, and performance optimisation. Built MCP server exposing RAP OData services as AI-controlled tools.', ARRAY['ABAP','CDS','AMDP','RAP','OData','Node.js','MCP','S/4HANA'], ARRAY['S/4HANA','AI','MCP','Performance'], 'projects/cba-trbk-hana.html', true, 1),
  ('Woolworths SAP CAR UDF High-Volume Processing', 'High-volume forecasting and machine-learning reporting', 'Woolworths', 'Processed more than 40 billion records across partitioned tables.', 'Led SAP CAR UDF custom developments for forecast calculations and ML reporting. Built high-volume AMDP, CDS, and ABAP objects with performance optimisation via SQL Trace, AMDP Trace, and PlanViz.', ARRAY['AMDP','CDS','ABAP','SAP CAR','SQL Trace','PlanViz'], ARRAY['Performance','High-volume','S/4HANA'], 'projects/woolworths-car-udf.html', false, 2),
  ('Services Australia Financial Instruction Processing', 'S/4HANA financial instruction processing and real-time payments', 'Services Australia', 'Processed large volumes of financial instruction documents with real-time payment extensions and ML anomaly detection.', 'Designed and built solution using CDS-based BOPF, AMDP code pushdown, Gateway/OData/CDS APIs, and ABAP RESTful apps. Extended to process Real Time Payments with ML anomaly detection.', ARRAY['CDS','BOPF','AMDP','OData','Gateway','S/4HANA','Machine Learning'], ARRAY['S/4HANA','Finance','AI'], 'projects/services-australia-payments.html', true, 3),
  ('Stockland S/4HANA Planning and Analytics', 'S/4HANA, REFX, PPM, BW-IP, SAP UI5', 'Stockland', 'Delivered full BW-IP planning and analytics stack with Fiori applications and Analysis for Office integration.', 'Built ABAP/HANA BW-IP Planning functions, ADSO write-back flows, Analysis for Office integration, SAP UI5 applications, OData services, CDS, AMDP, and Fiori analytical annotations.', ARRAY['BW-IP','AMDP','CDS','SAP UI5','OData','Fiori','REFX','PPM'], ARRAY['S/4HANA','Analytics','Planning'], 'projects/stockland-planning.html', false, 4),
  ('AI-assisted SAP RAP Execution with MCP', 'Governed AI-assisted SAP automation', 'Commonwealth Bank', 'Exposed SAP RAP OData services as controlled tools through MCP, enabling AI-assisted business task execution.', 'Built a Node.js MCP server implementing Anthropic Model Context Protocol to expose SAP RAP OData services as governed tools. Enables AI assistants to execute SAP business tasks without direct GUI interaction.', ARRAY['Node.js','MCP','RAP','OData','TypeScript','Anthropic'], ARRAY['AI','MCP','Automation','SAP'], 'projects/mcp-rap-ai-automation.html', true, 5),
  ('SAP Labs Machine Learning and HANA Engineering', 'Predictive analytics, HANA native development', 'Mohawk, Mosaic, BMW, BHP', 'Built PAL/APL/R ML models for quality prediction, HANA native minefield visualisations, BMW SRM procurement add-ons, and BHP UI Logging extensions.', 'Mohawk: ML models using PAL, APL, R for carpet quality prediction (CRISP-DM). Mosaic: HANA native minefield borehole visualisation system. BMW: Custom SRM indirect procurement add-on. BHP: Custom SAP UI Logging solution on LOGWIN.', ARRAY['SAP HANA','PAL','APL','R','XSJS','XSODATA','SAP UI5','Web Dynpro ABAP'], ARRAY['AI','Machine Learning','HANA','Analytics'], 'projects/sap-labs-product-engineering.html', true, 6),
  ('Queensland Health Digital Passport', 'SAP BTP CAP application', 'Queensland Health', 'Consolidated employee information from SAP ECC and QHealth Platform into a unified BTP service layer.', 'Contributed to development of Digital Passport Application built using SAP BTP CAP model, consolidating employee information from multiple source systems.', ARRAY['SAP BTP','CAP','SAP ECC','Node.js'], ARRAY['BTP','CAP'], '', false, 7),
  ('Department of Corrections NZ — Procurement and Fiori', 'S/4HANA upgrade readiness, Fiori, clean core', 'Department of Corrections NZ', 'Delivered custom Fiori apps, clean-core remediation, and upgrade readiness artefacts.', 'Built custom analytical Fiori apps, activated standard apps, applied Adapt UI extensibility. Used SCMON, SUSG, and Custom Code Migration App for clean-core scoping and remediation.', ARRAY['SAP Fiori','ABAP','SCMON','SUSG','Adapt UI','Custom Code Migration'], ARRAY['S/4HANA','Clean Core','Fiori'], '', false, 8),
  ('DyFlex — Roy Hill and Syntax S/4HANA Transformation', 'S/4HANA custom code remediation and migration', 'Roy Hill, Syntax', 'Remediated custom code for S/4HANA compatibility across cloud and clean-core standards.', 'Remediated custom code, replaced obsolete objects, adapted enhancements for clean-core and cloud standards, and developed migration support artefacts.', ARRAY['ABAP','S/4HANA','Clean Core','ATC','Custom Code Migration'], ARRAY['S/4HANA','Clean Core'], '', false, 9),
  ('Real-Time Speech and Predictive Analytics — Patent US10304013B2', 'Hackathon — accessibility and AI', 'SAP Labs', 'Finalist SAP What the Hack 2.0. Granted US patent US10304013B2.', 'Designed and built a click-free Real Time Speech and Predictive Analytics application for differently enabled people using SAP HANA. Patent granted: US10304013B2.', ARRAY['SAP HANA','Speech Recognition','Predictive Analytics'], ARRAY['AI','Patent','Accessibility'], 'https://patents.google.com/patent/US10304013B2/en', true, 10);
