DELETE FROM experience;

INSERT INTO experience (company, client, role, location, start_date, end_date, description, technologies, sort_order) VALUES
  ('SAP Australia', 'Commonwealth Bank', 'Contractor', 'Sydney, Australia', 'Mar 2025', 'Nov 2025 & Jan 2026 - Current', 'Supported CommBank SAP Transactional Banking (TRBK HANA) modernisation as part of the core-banking transformation program. Contributed to code remediation and performance optimisation, resolving legacy issues and translating DB2 query hints to HANA equivalents. Built a Node.js-based MCP server to expose SAP RAP OData services as controlled tools, enabling AI-assisted execution of business tasks without direct SAP GUI interaction. Proposed, designed, and implemented a data scrambling solution for SAP S/4HANA using ABAP, CDS Views, and AMDPs, reducing runtime from 240 hours to 6 hours (97% improvement).', ARRAY['ABAP on HANA','CDS','AMDP','RAP','OData','Node.js','MCP','S/4HANA'], 1),
  ('DyFlex Solutions', 'Roy Hill, Syntax', 'Contractor', 'Sydney, Australia', 'Nov 2024', 'Feb 2025', 'Worked on S/4HANA transformation projects for Roy Hill and Syntax. Remediated custom code for S/4HANA compatibility, replaced obsolete objects, adapted enhancements to align with clean-core and cloud standards. Developed new artefacts to support migration and ensure system readiness.', ARRAY['ABAP','S/4HANA','Clean Core','Custom Code Migration','ATC'], 2),
  ('SAP Australia', 'Woolworths', 'Development Architect', 'Sydney, Australia', 'Jul 2022', 'Sep 2024', 'Led SAP CAR UDF custom developments at Woolworths, designing scalable solutions to support forecast data calculations and machine learning reporting. Built multiple high-volume custom objects using AMDP, CDS, and ABAP to process more than 40 billion records across several partitioned tables. Focused on performance optimisation through Code Inspector, SQL Trace, AMDP Trace, and PlanViz.', ARRAY['AMDP','CDS','ABAP','SAP CAR','SQL Trace','PlanViz','S/4HANA'], 3),
  ('SAP Australia', 'Queensland Health', 'Development Architect', 'Sydney, Australia', 'Jun 2023', 'Aug 2023', 'Contributed to development of Digital Passport Application built using SAP BTP CAP model, used to consolidate employee information from SAP ECC and QHealth Platform.', ARRAY['SAP BTP','CAP','SAP ECC','Node.js'], 4),
  ('SAP Australia', 'Department of Corrections NZ', 'Development Architect', 'Sydney, Australia', 'Sep 2022', 'Jun 2023', 'Worked on SAP Procurement developments as part of project upgrade preparation. Built Custom Analytical Fiori Apps, activated apps and assigned roles, leveraged key user extensibility using Adapt UI. Evaluated custom code using ABAP Call Monitor (SCMON) and SUSG, used Custom Code Migration App for scoping, remediation, and optimisation.', ARRAY['SAP Fiori','ABAP','SCMON','SUSG','Custom Code Migration App','Adapt UI'], 5),
  ('SAP Australia', 'Services Australia', 'Development Architect', 'Sydney, Australia', 'Nov 2018', 'Jun 2022', 'Development Architect for Services Australia. Contributed to Vision and Scope documents. Designed and built solutions to process large volumes of Financial Instruction Documents using CDS-based BOPF, AMDP code pushdown, and Gateway/OData/CDS APIs. Extended the solution to process Real Time Payments. Built machine learning solutions to identify payment anomalies.', ARRAY['CDS','BOPF','AMDP','OData','Gateway','ABAP RESTful','S/4HANA','Machine Learning'], 6),
  ('SAP Labs India', 'Stockland', 'Development Architect', 'Bangalore, India', 'Mar 2017', 'Jan 2018', 'Stockland uses PPM and REFX on SAP S/4HANA with BW Integrated Planning for financial forecasting. Participated in development of ABAP and HANA based BW-IP Planning functions, CDS and AMDP objects. Built ADSO with planning functions, Free Style SAP UI5 applications using OData and CDS, and end-to-end Fiori applications with OData Annotations.', ARRAY['BW-IP','AMDP','CDS','SAP UI5','OData','Fiori','REFX','PPM','S/4HANA'], 7),
  ('SAP Labs India', 'Mohawk, Mosaic, BMW, BHP', 'Senior Developer', 'Bangalore, India', 'Mar 2012', 'Jan 2018', 'Mohawk (Jan–Jul 2016): Data science and ML project for carpet quality prediction using PAL (Decision Tree), APL (Regression), and R (Random Forest) models. Followed CRISP-DM methodology. Mosaic (Aug 2015–Jan 2016): SAP HANA native development for minefield visualisations. BMW GSM (Sep 2014–Mar 2017): Custom add-on for indirect procurement in SRM. BHP UI Logging (Mar 2012–Aug 2014): Custom SAP UI Logging solution on top of LOGWIN.', ARRAY['SAP HANA','PAL','APL','R','SAP UI5','XSJS','XSODATA','Web Dynpro ABAP','SRM','ABAP'], 8),
  ('Logikal Consulting, Deloitte, IBM, Enteg InfoTech', 'Standard Bank, Deutsche Bank, Suzlon, Nationwide Building Society', 'SAP ABAP Specialist / Senior Developer', 'South Africa, India', 'Jul 2007', 'Jan 2012', 'Worked across SD, MM, FI, HR, Banking, and ReFX for multiple clients. Delivered ABAP, ABAP HR, and Web Dynpro ABAP artefacts including RICEF, Infotypes, dashboard reports, and custom Web Dynpro ABAP applications.', ARRAY['ABAP','ABAP HR','Web Dynpro ABAP','RICEF','SD','MM','FI','HR','Banking','ReFX'], 9);
